# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: 0.{build}
build:
  verbosity: minimal

branches:
  only:
    - main

skip_branch_with_pr: true
test: off
stack: python 3.10.8

environment:
  GITHUB_TOKEN:
    # * https://ci.appveyor.com/tools/encrypt
    secure: h4A1e3+KTJ+h28Rv9IMSX6fyXBAvLETjfMv5tjXB3y7cZq+Kxg60myRpuVeG24Ei
  APPVEYOR_REPO_TAG: true

deploy:
  - provider: GitHub
    auth_token: $(GITHUB_TOKEN)

image:
  - Visual Studio 2019
  - macOS
  - Ubuntu

install:
  - pip install -r requirements.txt

# ! Standart Derleme Komutu ("WinÇöp Hariç")
build_script:
  - pyinstaller basla.py --name ntvHaber --noconsole --noconfirm --onefile --add-data "Assets:Assets" --icon "Assets/favicon.ico" --collect-all certifi

# * » Windows paketi
for:
  - matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a ntvHaber-windows.zip %CD%\dist\*.exe

    build_script:
      - pyinstaller basla.py --name ntvHaber --noconsole --noconfirm --onefile --add-data "Assets;Assets" --icon "Assets/favicon.ico" --collect-all certifi

    artifacts:
      - path: ntvHaber-windows.zip

  # * » macOS paketi
  - matrix:
      only:
        - image: macOS

    before_build:
      - pip3 install Pillow

    after_build:
      - tar -czvf ntvHaber-macos.tar.gz -C dist ntvHaber.app

    artifacts:
      - path: ntvHaber-macos.tar.gz

  # * » Linux paketi
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf ntvHaber-linux.tar.gz -C dist ntvHaber

    artifacts:
      - path: ntvHaber-linux.tar.gz